tap "buo/cask-upgrade"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "jhawthorn/fzy"
tap "neovim/neovim"

brew "bash"
brew "brew-cask-completion"
brew "coreutils"
brew "findutils"
brew "fish"
brew "fzf"
brew "git"
brew "gnu-sed"
brew "htop"
brew "neovim", args: ["HEAD"]
brew "python"
brew "ripgrep"
brew "tidy-html5"
brew "tmux", args: ["HEAD"]
brew "trash"
brew "tree"
brew "watchman"
brew "wget"
brew "mackup"
brew "bat"
brew "asdf"
brew "diff-so-fancy"
brew "rename"

cask_args appdir: "/Applications"
cask "docker"
cask "dropbox"
cask "firefox"
cask "firefox-developer-edition"
cask "google-backup-and-sync"
cask "google-cloud-sdk"
cask "google-chrome"
cask "google-chrome-canary"
cask "hacker-menu"
cask "insomnia"
cask "iterm2-nightly"
cask "karabiner-elements"
cask "skype"
cask "suspicious-package"
cask "the-unarchiver"
cask "transmission"
cask "whatsapp"
cask "adobe-creative-cloud"
cask "adobe-acrobat-reader"
cask "gpg-suite"
cask "amethyst"
cask "alacritty"

# Quick look plugins
cask "webpquicklook"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
