- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config', '~/Library/Application Support/Code - Insiders/User']

- link:
    ~/.ctags:
    ~/.editorconfig:
    ~/.gitattributes:
    ~/.gitconfig:
    ~/.gitignore:
    ~/.prettierrc:
    ~/.tern-project:
    ~/.config/fish: fish
    ~/.config/karabiner: karabiner
    ~/.config/nvim: neovim
    ~/.config/alacritty: alacritty
    ~/.tmux.conf: tmux/tmux.conf
    '~/Library/Application Support/Code - Insiders/User/custom.css': vscode/custom.css
    '~/Library/Application Support/Code - Insiders/User/keybindings.json': vscode/keybindings.json
    '~/Library/Application Support/Code - Insiders/User/settings.json': vscode/settings.json
    '~/Library/Application Support/Code - Insiders/User/snippets': vscode/snippets
