- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.asdfrc:
    ~/.mackup.cfg:
    ~/.mackup:
    ~/.editorconfig:
    ~/.gitattributes:
    ~/.gitconfig:
    ~/.gitignore:
    ~/.prettierrc:
    ~/.stylelintrc.js:
    ~/.config/fish: fish
    ~/.config/karabiner: karabiner
    ~/.config/nvim: neovim
    ~/.config/alacritty: alacritty
    ~/.config/kitty: kitty
    ~/.config/htop/htoprc: htoprc
    ~/.tmux.conf: tmux/tmux.conf
