- shell:
  -
    command: scripts/xcode
    stderr: true
    description: Xcode
  -
    command: scripts/homebrew
    stderr: true
    description: Homebrew
  -
    command: scripts/terminal
    stderr: true
    description: Terminal colors setup
  -
    command: scripts/macos
    stdout: true
    stderr: true
    description: MacOS defaults
  -
    command: brew bundle
    stderr: true
    stdout: true
    description: Install brew bundles
  -
    command: scripts/asdf
    stderr: true
    description: Install asdf versions of nodejs/go/rust
  -
    command: scripts/neovim
    stderr: true
    description: Neovim plugins
  -
    command: scripts/tmux
    stderr: true
    description: Tmux plugins
  -
    command: scripts/yarn
    stderr: true
    description: Yarn global
  -
    command: curl https://sh.rustup.rs -sSf | sh -s -- -y
    stderr: true
    description: Cargo/Rust
  -
    command: scripts/mackup
    stdout: true
    stderr: true
    description: Mackup restore
