- shell:
  - [git submodule update --init --recursive, git submodules]
  -
    command: scripts/xcode
    stderr: true
    description: Xcode
  -
    command: scripts/terminal
    stderr: true
    description: Terminal colors setup
  -
    command: scripts/alacritty
    stderr: true
    stdout: true
    description: Install Alacritty

- brewfile:
  - Tapfile
  - Brewfile
  - Caskfile
  - Macfile

- shell:
  -
    command: |
      pip2 install --user neovim vim-vint
      pip3 install --user neovim vim-vint
    stderr: true
    description: Pip
  -
    command: nvim +PlugInstall +qall
    stderr: true
    description: Neovim plugins
  -
    command: |
      git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
      ~/.tmux/plugins/tpm/bin/install_plugins
    stderr: true
    description: Tmux plugins
  -
    command: |
      curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
      fisher
    stderr: true
    description: Fisher
  -
    command: sudo gem install coderay
    stderr: true
    stdin: true
    description: Coderay
  -
    command: scripts/yarn
    stderr: true
    description: Yarn global
  -
    command: scripts/vscode
    stderr: true
    description: Visual Studio Code extensions
