- shell:
  - [git submodule update --init --recursive, git submodules]
  -
    command: scripts/xcode
    stderr: true
    description: Xcode
  -
    command: scripts/homebrew
    stderr: true
    description: Homebrew
  -
    command: scripts/terminal
    stderr: true
    description: Terminal colors setup
  -
    command: brew bundle
    stderr: true
    stdout: true
    description: Install brew bundles
  -
    command: N_PREFIX=$HOME/.n n latest
    stderr: true
    stdout: true
    description: Install nodeJS
  -
    command: scripts/neovim
    stderr: true
    description: Neovim plugins
  -
    command: scripts/tmux
    stderr: true
    description: Tmux plugins
  -
    command: scripts/yarn
    stderr: true
    description: Yarn global
  -
    command: scripts/macos
    stdout: true
    stderr: true
    description: MacOS defaults
  -
    command: scripts/mackup
    stdout: true
    stderr: true
    description: Mackup restore
