- shell:
  - [git submodule update --init --recursive, git submodules]
  -
    command: scripts/xcode
    stderr: true
    description: Xcode
  -
    command: scripts/homebrew
    stderr: true
    description: Homebrew
  -
    command: scripts/terminal
    stderr: true
    description: Terminal colors setup
  -
    command: scripts/alacritty
    stderr: true
    stdout: true
    description: Install Alacritty
  -
    command: brew bundle
    stderr: true
    stdout: true
    description: Install brew bundles
  -
    command: |
      pip2 install --user neovim vim-vint
      pip3 install --user neovim vim-vint
    stderr: true
    description: Pip
  -
    command: nvim +PlugInstall +qall
    stderr: true
    description: Neovim plugins
  -
    command: scripts/tmux
    stderr: true
    description: Tmux plugins
  -
    command: scripts/fisher
    stderr: true
    description: Fisher
  -
    command: sudo gem install coderay neovim
    stdin: true
    description: Coderay
  -
    command: scripts/yarn
    stderr: true
    description: Yarn global
  -
    command: scripts/vscode
    stderr: true
    description: Visual Studio Code extensions
