- shell:
  # - [mas upgrade, Update mac apps]
  - [fish -c "fisher up", Update Fish plugins]
  - [yarn global upgrade --ignore-engines, Update Yarn global]
  - [pip2 install --upgrade neovim vim-vint; pip3 install --upgrade neovim vim-vint, Update pip]
  - [~/.tmux/plugins/tpm/bin/update_plugins all, Update tmux plugins]
  -
    command: brew upgrade --fetch-HEAD
    description: Update formulaes
    stdout: true
    stderr: true
  -
    command: brew cu --no-brew-update -ay
    description: Update casks
    stdout: true
    stderr: true
  -
    command: nvim +"Dein update" +qall; and nvim +UpdateRemotePlugins +qall
    stdout: true
    stderr: true
    description: Update nvim plugins
