- brewfile:
  - Tapfile
  - Brewfile

- shell:
  - [brew cu --no-brew-update -ay, Update casks]
  - [mas upgrade, Update mac apps]
  - [fish -c "fisher up", Update Fish plugins]
  - [yarn global upgrade, Update Yarn global]
  - [pip2 install --upgrade neovim vim-vint; pip3 install --upgrade neovim vim-vint, Update pip]
  - [~/.tmux/plugins/tpm/bin/update_plugins all, Update tmux plugins]
  -
    command: nvim +PlugUpdate +qall
    stderr: true
    description: Update nvim plugins
