#!/usr/bin/env bash

brew_install_or_upgrade dockutil
brew_install_or_upgrade trash
brew_install_or_upgrade tree
brew_install_or_upgrade wget
brew_install_or_upgrade https://raw.githubusercontent.com/choppsv1/homebrew-term24/master/tmux.rb
brew_install_or_upgrade neovim --HEAD
brew_install_or_upgrade zsh
brew_install_or_upgrade git
brew_install_or_upgrade nvm
brew_install_or_upgrade ack
brew_install_or_upgrade ag
brew_install_or_upgrade reattach-to-user-namespace
brew_install_or_upgrade highlight
