#!/usr/bin/env bash


# Install GNU core utilities (those that come with OS X are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew_install_or_upgrade coreutils
sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

# Install some other useful utilities like `sponge`.
brew_install_or_upgrade moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew_install_or_upgrade findutils
# Install GNU `sed`, overwriting the built-in `sed`.
brew_install_or_upgrade gnu-sed --with-default-names
# Install Bash 4.
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before
# running `chsh`.
brew_install_or_upgrade bash
brew tap homebrew/versions
brew_install_or_upgrade bash-completion2

brew_install_or_upgrade dockutil
brew_install_or_upgrade trash
brew_install_or_upgrade tree
brew_install_or_upgrade wget --with-iri
brew_install_or_upgrade https://raw.githubusercontent.com/choppsv1/homebrew-term24/master/tmux.rb
brew_install_or_upgrade neovim --HEAD
brew_install_or_upgrade zsh
brew_install_or_upgrade git
brew_install_or_upgrade nvm
brew_install_or_upgrade ack
brew_install_or_upgrade ag
brew_install_or_upgrade reattach-to-user-namespace
brew_install_or_upgrade highlight
brew_install_or_upgrade vim --override-system-vi
brew_install_or_upgrade homebrew/dupes/grep
brew_install_or_upgrade homebrew/dupes/openssh
brew_install_or_upgrade homebrew/dupes/screen

# Install font tools.
brew tap bramstein/webfonttools
brew_install_or_upgrade sfnt2woff
brew_install_or_upgrade sfnt2woff-zopfli
brew_install_or_upgrade woff2
brew_install_or_upgrade dark-mode

brew cleanup