#!/bin/bash

source $DOTFILES_DIR/lib/utils.sh

apps=(
  gulp
  react-native-cli
  eslint
  zelphir/eslint_d.js
  rnpm
  npm-check
)

if !(type_exists $HOME/.n/bin/${apps[@]}); then
  $HOME/.n/bin/npm install -g ${apps[@]}
fi
