#!/usr/bin/env bash

# reload nvm into this environment
NVM_DIR=$HOME/.nvm
NVM_IOJS_RC_PREFIX=""
NVM_ADD_SYSTEM=""

source $(brew --prefix nvm)/nvm.sh

if [ ! -d "$HOME/.nvm" ]; then
  mkdir $HOME/.nvm
fi

nvm install stable
nvm install 4.2
nvm alias default stable
nvm use default
