#!/usr/bin/env bash

# reload nvm into this environment
NVM_DIR=$HOME/.nvm

source $(brew --prefix nvm)/nvm.sh

if [ ! -d "$HOME/.nvm" ]; then
  mkdir $HOME/.nvm
fi

nvm install 4.2
nvm install stable
nvm alias default stable
