#!/usr/bin/env bash

PREVDIR=$(pwd)
tmp=$(mktemp -d)

if ! type 'cargo' &> /dev/null; then
  curl -sSf https://static.rust-lang.org/rustup.sh | sh
fi

if [ ! -d "/Applications/Alacritty.app" ]; then
  cd $tmp
  git clone https://github.com/jwilm/alacritty.git
  cd alacritty
  cargo build --release
  make app
  cp -r target/release/osx/Alacritty.app /Applications/Alacritty.app
fi

cd $PREVDIR
