#!/usr/bin/env bash

# NodeJS/Yarn - latest version
LATEST_NODE=`asdf list-all nodejs | tail -1`
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
asdf install nodejs $LATEST_NODE
asdf global nodejs $LATEST_NODE
curl -o- -L https://yarnpkg.com/install.sh | bash

# Go - latest version
LATEST_GO=`asdf list-all golang | tail -1`
asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
asdf install golang $LATEST_GO
asdf global golang $LATEST_GO

# Rust - latest version
# LATEST_RUST=`asdf list-all rust | tail -1`
# asdf plugin-add rust https://github.com/code-lever/asdf-rust.git
# asdf install rust $LATEST_RUST
# asdf global rust $LATEST_RUST
