#!/usr/bin/env bash

pip install neovim vim-vint
# pip3 install neovim vim-vint

nvim -V1 -es -i NONE -N -u $HOME/.config/nvim/init.vim -c "try | call dein#update() | finally | echomsg '' | qall! | endtry"
