#!/usr/bin/env bash

if [ ! -e "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

~/.tmux/plugins/tpm/bin/install_plugins

mkdir -p "$(bat --config-dir)/themes" && cd "$(bat --config-dir)/themes"
git clone https://github.com/mhartington/oceanic-next-iterm
bat cache --build
