#!/usr/bin/env bash

EXTENSIONS=$(cat ~/.dotfiles/vscode/extensions)

defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false

for extension in $EXTENSIONS; do
  code --install-extension $extension
done
