#!/usr/bin/env bash

export PATH=$HOME/.n/bin:$PATH

apps=(
  @google-cloud/functions-emulator
  create-react-app
  create-react-native-app
  firebase-tools
  gqlint
  graphcool
  jsctags
  livedown
  neovim
  prettier
  react-native-cli
  serve
  tern
)

yarn global add ${apps[@]}
