#!/usr/bin/env bash

apps=(
  create-react-app
  create-react-native-app
  exp
  firebase-tools
  jsctags
  livedown
  neovim
  prettier
  react-native-cli
  serve
  tern
)

yarn global add ${apps[@]}
