# Lazy loaded

# Syntax
[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
hook_add = 'let g:used_javascript_libs = "underscore,react"'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']
on_source = ['othree/yajs.vim', 'HerringtonDarkholme/yats.vim']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'jsx']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescript.tsx', 'typescriptreact', 'tsx']

[[plugins]]
repo = 'neoclide/vim-jsx-improve'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']

# Utils
[[plugins]]
repo = 'Yggdroot/indentLine'
on_ft = ['python', 'html', 'css', 'vim', 'javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']
hook_source = 'source $NVIM_HOME/layers/ui/indentline/config.vim'

[[plugins]]
repo = 'rhysd/accelerated-jk'
# on_map = {n = '<Plug>'}

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_map = {n = '<Plug>'}

[[plugins]]
repo = 'tpope/vim-repeat'
# on_map = '.*'

[[plugins]]
repo = 'junegunn/fzf.vim''
depends = 'fzf'
on_cmd = ['History', 'Rg', 'Buffers', 'GFiles', 'Snippets']
on_func = 'Fzf_dev'
hook_source = 'source $NVIM_HOME/layers/completition/fzf/config.vim'

[[plugins]]
repo = 'chemzqm/vim-easygit'
on_cmd = ['Gcd', 'Glcd', 'Gcommit', 'Gblame', 'Gstatus', 'Gdiff', 'Gbrowse', 'Gstatus', 'Gpush']
hook_source = 'let g:easygit_enable_command = 1'
