# Lazy loaded

# Syntax
# [[plugins]]
# repo = 'othree/javascript-libraries-syntax.vim'
# hook_add = 'let g:used_javascript_libs = "underscore,react"'
# on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']
# on_source = ['othree/yajs.vim', 'HerringtonDarkholme/yats.vim']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']

# [[plugins]]
# repo = 'othree/yajs.vim'
# on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'jsx']

# [[plugins]]
# repo = 'leafgarland/typescript-vim'
[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescript.tsx', 'typescriptreact', 'tsx']

[[plugins]]
repo = 'neoclide/vim-jsx-improve'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx', 'graphql']

# Utils
[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_map = {n = '<Plug>'}

[[plugins]]
repo = 'junegunn/fzf.vim''
depends = 'fzf'
on_cmd = ['Colors', 'History', 'F', 'Rg', 'Buffers']
on_func = ['Fzf_dev', 'Fzf_git_dev']
hook_source = 'source $NVIM_HOME/layers/completition/fzf/config.vim'

[[plugins]]
repo = 'brooth/far.vim'
on_cmd = ['Far']
hook_add = '''
let g:far#window_layout = "current"
let g:far#preview_window_height = &lines/2
let g:far#source = "rgnvim"
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_ft = ['vim', 'json', 'go', 'html', 'css', 'toml', 'xml', 'Dockerfile', 'Makefile']

[[plugins]]
repo = 'kizza/actionmenu.nvim'
on_path = '.*'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
build = 'GoUpdateBinaries'
