[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo= '/usr/local/opt/fzf'
merged= 0

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = [
\ 'markdown',
\ 'javascript',
\ 'javascript.jsx',
\ 'javascriptreact',
\ 'typescript',
\ 'typescript.tsx',
\ 'typescriptreact',
\ 'jsx',
\ 'tsx']
'''

[[plugins]]
repo = 'mhartington/oceanic-next'
# repo = '/Volumes/Workspace/oceanic-next-ext'
hook_add = '''
let g:oceanic_next_terminal_bold = 1
let g:oceanic_next_terminal_italic = 1
'''

[[plugins]]
repo = 'lifepillar/vim-colortemplate'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'yarn install --frozen-lockfile'
merged = 0
hook_add = 'source $NVIM_HOME/layers/completition/coc/config.vim'

[[plugins]]
repo = 'rrethy/vim-hexokinase'
build = 'make hexokinase'

[[plugins]]
repo = 'tomtom/tcomment_vim'

# Integration with tmux
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events'

# Snippets
[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'gorkunov/smartpairs.vim'

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Valloric/MatchTagAlways'

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'matze/vim-move'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:EasyMotion_prompt = "Jump to → "
let g:EasyMotion_keys = "fjdkswbeoavn"
let g:EasyMotion_smartcase = 1
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'junegunn/rainbow_parentheses.vim'
hook_add = """
let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}']]
"""

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_source = 'source $NVIM_HOME/layers/ui/indentline/config.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
merged = 0
