# Lazy loaded

# Snippets
[[plugins]]
repo = 'honza/vim-snippets'
depends = 'coc.nvim'

# Syntax
[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
hook_add = 'let g:used_javascript_libs = "underscore,react"'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']
on_source = ['othree/yajs.vim', 'HerringtonDarkholme/yats.vim']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'jsx']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescript.tsx', 'typescriptreact', 'tsx']

[[plugins]]
repo = 'neoclide/vim-jsx-improve'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = 'vim-devicons'
hook_source = '''
source $NVIM_HOME/layers/completition/denite/config.vim
source $NVIM_HOME/layers/completition/denite/denite_menu.vim
'''

# Utils
[[plugins]]
repo = 'Yggdroot/indentLine'
on_ft = ['python', 'html', 'css', 'vim', 'javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'jsx', 'tsx']
hook_source = 'source $NVIM_HOME/layers/ui/indentline/config.vim'

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = ['n: <Plug>']

# [[plugins]]
# repo = 'ludovicchabant/vim-gutentags'
# if = 'executable("ctags")'
# on_path = '.*'
# hook_source = 'source $NVIM_HOME/layers/tools/vim-gutentags/config.vim'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_map = ['n: <Plug> }']

[[plugins]]
repo = 'tpope/vim-repeat'
on_map = ['.*']

[[plugins]]
repo = 'junegunn/fzf.vim''
depends = 'fzf'
on_cmd = ['Colors','Rg,Buffers']
on_func = 'Fzf_dev'
hook_source = 'source $NVIM_HOME/layers/completition/fzf/config.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'
